export const ASTAG = {
    '無': '',
    '攻擊': 'AS_attack',
    '連擊': 'ASRushAttack',
    '屬性特效': 'AS_attribute_critical',
    '屬性特效連擊': 'AS_attribute_critical_rush',
    '種族特效': 'AS_breed_critical',
    '分散攻擊': 'AS_attack_all_split',
    '全體攻擊': 'AS_zentai_power',
    '賭博攻擊': 'ASGamble',
    '吸收': 'ASAbsorption',
    '連鎖攻擊': 'AS_combo_power_up',
    '瀕死攻擊': 'AS_dying_power_up',
    '精神抖擻攻擊': 'AS_good_health_power_up',
    '強化攻擊': 'AS_attack_enhance',
    '悲嘆的憤怒': 'AS_anger',
    '問題類型顏色數攻擊': 'AS_quiz_attribute_count',
    '屬性的庇佑': 'AS_deck_attribute_power_up',
    '強化種族攻擊': 'AS_breed_enhance',
    '種族數攻擊': 'AS_breed_attack_up',
    '回復/自身': 'ASRecover',
    '回復': 'ASRecover',
    '連段數回復': 'AS_combo_cure',
    '防禦': 'AS_guard',
    '強化複屬性攻擊': 'AS_attribute_enhance',
    '種族特效(全體)': 'AS_breed_critical',
    '技能複製': ''
};