export const PROPS = [
  { value: '火', label: '火屬性' },
  { value: '水', label: '水屬性' },
  { value: '雷', label: '雷屬性' },
  { value: '光', label: '光屬性' },
  { value: '闇', label: '闇屬性' },
];
export const PROPS2 = [
  { value: '火', label: '火屬性' },
  { value: '水', label: '水屬性' },
  { value: '雷', label: '雷屬性' },
  { value: '光', label: '光屬性' },
  { value: '闇', label: '闇屬性' },
];
export const BREEDS = [
  { value: '龍族', label: '龍族' },
  { value: '神族', label: '神族' },
  { value: '魔族', label: '魔族' },
  { value: '天使', label: '天使' },
  { value: '妖精', label: '妖精' },
  { value: '亞人', label: '亞人' },
  { value: '物質', label: '物質' },
  { value: '魔法生物', label: '魔法生物' },
  { value: '戰士', label: '戰士' },
  { value: '術士', label: '術士' },
  { value: '道具', label: '道具' },
  { value: 'AbCd', label: 'AbCd' },
  { value: '鬥士', label: '鬥士' },
  { value: '王族', label: '王族' },
  { value: '機械', label: '機械' },
];
export const RANKS = [
  // { value: 'X', label: '只列出最終進化' },
  { value: 'LtoL', label: 'LtoL' },
  { value: 'L', label: 'L' },
  { value: 'SS+', label: 'SS+' },
  { value: 'SS', label: 'SS' },
  { value: 'S+', label: 'S+' },
  { value: 'S', label: 'S' },
  { value: 'A+', label: 'A+' },
  { value: 'A', label: 'A' },
  { value: 'B+', label: 'B+' },
  { value: 'B', label: 'B' },
  { value: 'C+', label: 'C+' },
];
