export const cardNotFoundTemplate = {
  obtainType: {
    id: '1',
    title: '友情轉蛋',
    type: 'haifu',
  },
  id: '',
  prop: '',
  prop2: '',
  breed: '',
  rank: '',
  name: '',
  max_hp: '0',
  max_atk: '0',
  cost: '0',
  card_filename: '0000.png',
  small_filename: '0000.png',
  evo_now: '',
  evo_max: '',
  as: '',
  ss: '',
  as2: '',
  ss2: '',
  senzai_1: '',
  senzai_2: '',
  senzai_3: '',
  senzai_4: '',
  senzai_5: '',
  senzai_6: '',
  senzai_7: '',
  senzai_8: '',
  senzai_9: '',
  senzai_10: '',
  senzaiL_1: '',
  senzaiL_2: '',
  senzaiL_3: '',
  senzaiL_4: '',
  evo_1: '',
  evo_2: '',
  evo_3: '',
  evo_4: '',
  evo_5: '',
  evo_6: '',
  evo_7: '',
  evo_8: '',
  evo_price: '',
  sell_price: '',
  evo_from: '',
  evo_to: '',
  evo_chain_before_note: '',
  evo_chain_after_note: '',
  evo_chain_branch: '',
  get_source: '',
  comment: '',
  evoArr: [],
  senzaiArr: [],
  senzaiLArr: [],
  asData: {
    name: '無',
    info: '',
    type: '無',
    attrs: [],
  },
  ssData: {
    name: '無',
    info: '',
    type: '無',
    attrs: [],
    cdf: 99,
    cds: 99,
  },
  as2Data: {
    name: '無',
    info: '',
    type: '無',
    attrs: [],
  },
  ss2Data: {
    name: '無',
    info: '',
    type: '無',
    attrs: [],
    cdf: 99,
    cds: 99,
  },
};

export const exCardNotFoundTemplate = {
  id: '',
  prop: '',
  prop2: '',
  breed: '',
  rank: '',
  name: '',
  max_hp: '100',
  max_atk: '100',
  cost: '1',
  card_filename: '0000.png',
  small_filename: '0000.png',
  evo_now: '',
  evo_max: '',
  as: '',
  ss: '',
  as2: '',
  ss2: '',
  senzai_1: '',
  senzai_2: '',
  senzai_3: '',
  senzai_4: '',
  senzai_5: '',
  senzai_6: '',
  senzai_7: '',
  senzai_8: '',
  senzai_9: '',
  senzai_10: '',
  senzaiL_1: '',
  senzaiL_2: '',
  senzaiL_3: '',
  senzaiL_4: '',
  evo_1: '',
  evo_2: '',
  evo_3: '',
  evo_4: '',
  evo_5: '',
  evo_6: '',
  evo_7: '',
  evo_8: '',
  evo_price: '',
  sell_price: '',
  evo_from: '',
  evo_to: '',
  mutual_evo: '',
  evo_chain_before_note: '',
  evo_chain_after_note: '',
  evo_chain_branch: '',
  get_source: '',
  comment: '',
  attachCost: 0,
};

export const senzaiNotFoundTemplate = {
  name: '無',
  info: '',
  type: '無',
  filename: 'Senzai_NONE.png',
  attrs: [],
};

export const leaderEXCardNotFoundTemplate = {
  name: '無',
  rank: '',
  small_filename: '0000.png',
  condition: '',
  skill: '',
};
