export const ASTAG = {
    '無': '',
    '攻擊': 'AS_attack',
    '連擊': 'ASRushAttack',
    '屬性特效': 'AS_attribute_critical',
    '屬性特效連擊': 'AS_attribute_critical_rush',
    '種族特效': 'AS_breed_critical',
    '分散攻擊': 'AS_attack_all_split',
    '全體攻擊': 'AS_zentai_power',
    '賭博攻擊': 'ASGamble',
    '吸收': 'ASAbsorption',
    '連鎖攻擊': 'AS_combo_power_up',
    '瀕死攻擊': 'AS_dying_power_up',
    '精神抖擻攻擊': 'AS_good_health_power_up',
    '強化攻擊': 'AS_attack_enhance',
    '悲嘆的憤怒': 'AS_anger',
    '問題類型顏色數攻擊': 'AS_quiz_attribute_count',
    '屬性的庇佑': 'AS_deck_attribute_power_up',
    '強化種族攻擊': 'AS_breed_enhance',
    '種族數攻擊': 'AS_breed_attack_up',
    '回復/自身': 'ASRecover',
    '回復': 'ASRecover',
    '連段數回復': 'AS_combo_cure',
    '防禦': 'AS_guard',
    '強化複屬性攻擊': 'AS_attribute_enhance',
    '種族特效(全體)': 'AS_breed_critical',
    '技能複製': ''
};

export const EXASTAG = {
    '無': '',
    '反擊': 'EXAS_Label_ActionReflection',
    '攻擊': 'EXAS_Label_Attack',
    '攻擊強化': 'EXAS_Label_Attack_Enhance',
    '副屬性攻擊強化': 'EXAS_Label_Attribute_Enhance',
    '連鎖增加': 'EXAS_Label_ChainPlus',
    '全體化': 'EXAS_Label_ChangeAttackAll',
    '連續化': 'EXAS_Label_ChangeRush',
    '連鎖攻擊': 'EXAS_Label_Combo_Power_Up',
    '阻隔傷害': 'EXAS_Label_DamageBlock',
    '瀕死攻擊': 'EXAS_Label_DyingPowerUp',
    '屬性特效': 'EXAS_Label_Elemens_SAttack',
    '賭博攻擊': 'EXAS_Label_Gamble_Attack',
    '防禦': 'EXAS_Label_Guard',
    '貫穿': 'EXAS_Label_Penetrate',
    '狀態特效': 'EXAS_Label_PositiveBuffCritical',
    '追擊': 'EXAS_Label_PursueAttack',
    '回復': 'EXAS_Label_Recover',
    '連擊': 'EXAS_Label_Rush_Attack'
};